name: Rust CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref }}
      RELEASE_NAME: ${{ github.ref }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release&&ls target/release

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Changes in this release:
            - First version

            Commit SHA: ${{ env.COMMIT_SHA }}

            Commit URL: https://github.com/jsdvjx/shell_entry/commit/${{ env.COMMIT_SHA }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.P_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/shell_entry
          asset_name: shell_entry
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.P_TOKEN}}